"""initial

Revision ID: 8165ffcf4573
Revises:
Create Date: 2026-06-20 15:46:00.576670

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from models.utils import type_decorator_uuid

# revision identifiers, used by Alembic.
revision: str = "8165ffcf4573"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "uuid",
            type_decorator_uuid.UUIDString(length=36),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=24), nullable=False),
        sa.Column("password", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "meals",
        sa.Column(
            "uuid",
            type_decorator_uuid.UUIDString(length=36),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=24), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("is_diet", sa.Boolean(), nullable=False),
        sa.Column(
            "user_id",
            type_decorator_uuid.UUIDString(length=36),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meals")
    op.drop_table("users")
    # ### end Alembic commands ###
