class AUTH_STATUS_CODE:
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR"
    AUTH_LOGOFF_SUCCESS = "AUTH_LOGOFF_SUCCESS"
