class MEAL_STATUS_CODE:
    MEAL_CREATED = "MEAL_CREATED"
    MEAL_UPDATED = "MEAL_UPDATED"
    MEAL_NOT_UPDATED = "MEAL_NOT_UPDATED"
    MEAL_DELETED = "MEAL_DELETED"
    MEAL_NOT_FOUND = "MEAL_NOT_FOUND"
